name: ci-prod.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Test using MSTest

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    # Uncomment to enable testing
    # - name: Test with the dotnet CLI
    #   run: dotnet test

  deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Create MSIX package artifact
    needs: [test]
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, x86]

    runs-on: windows-latest

    env:
      Solution_Name: MageWin.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Generate a self-signed certificate
      run: |
        $cert = New-SelfSignedCertificate -DnsName "GitHubActionsWorkflow" -CertStoreLocation "cert:\LocalMachine\My"
        $pwd = ConvertTo-SecureString -String "${{ secrets.CERTIFICATEPASSWORD }}" -Force -AsPlainText
        Export-PfxCertificate -Cert $cert -FilePath "./GitHubActionsWorkflow.pfx" -Password $pwd
        Export-Certificate -Cert $cert -FilePath "./GitHubActionsWorkflow.crt"
      shell: pwsh

    # - name: Decode and Import the PFX certificate
    #   run: |
    #     $pfxBase64 = "${{ secrets.BASE64_ENCODED_PFX }}"
    #     $pfxPassword = "${{ secrets.PFX_CERT_PASSWORD }}"
    #     $pfxPath = "GitHubActionsWorkflow.pfx"
    #     $pfxPasswordSecure = ConvertTo-SecureString -String $pfxPassword -Force -AsPlainText
    #     [System.Convert]::FromBase64String($pfxBase64) | Set-Content $pfxPath -AsByteStream
    #     Import-PfxCertificate -FilePath $pfxPath -CertStoreLocation Cert:\CurrentUser\My -Password $pfxPasswordSecure

    - name: Build and create app package without signing
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:AppxPackageDir="$env:Appx_Package_Dir" /p:GenerateAppxPackageOnBuild=true
      env:
        Appx_Bundle: Never
        Appx_Package_Build_Mode: SideloadOnly
        Appx_Package_Dir: ./AppPackages/
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
      shell: pwsh

    - name: Install Windows SDK for SignTool
      run: |
        $package = 'windows-sdk-10'
        $installedPackages = choco list --local-only
        if ($installedPackages -like "*$package*") {
          Write-Host "Package $package is already installed."
        } else {
          choco install $package -y --verbose
        }
      shell: pwsh

    - name: Sign MSIX package with self-signed certificate
      run: |
        # Dynamically find the latest version of the Windows SDK to get the signtool path
        $sdkPath = Get-ChildItem -Path "${env:ProgramFiles(x86)}\Windows Kits\10\bin\" -Directory | Sort-Object Name -Descending | Select-Object -First 1
        $signtoolPath = Join-Path -Path $sdkPath.FullName -ChildPath "x64\signtool.exe"
        
        if (Test-Path $signtoolPath) {
          $msixFiles = Get-ChildItem -Path ./AppPackages/ -Recurse -Filter *.msix
          foreach ($file in $msixFiles) {
            & $signtoolPath sign /v /fd SHA256 /f "./GitHubActionsWorkflow.pfx" /p "${{ secrets.CERTIFICATEPASSWORD }}" $file.FullName
          }
        } else {
          Write-Error "SignTool not found at path: $signtoolPath"
        }
      shell: pwsh


    # - name: Create the app package
    #   run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=$pfxPath /p:PackageCertificatePassword=$pfxPassword /p:AppxPackageDir="$env:Appx_Package_Dir" /p:GenerateAppxPackageOnBuild=true
    #   env:
    #     Appx_Bundle: Never
    #     Appx_Package_Build_Mode: SideloadOnly
    #     Appx_Package_Dir: ./AppPackages/
    #     Configuration: ${{ matrix.configuration }}
    #     Platform: ${{ matrix.platform }}

    # - name: Create the unsigned app package
    #   run: |
    #     msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxPackageDir="$env:Appx_Package_Dir" /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=false
    #   env:
    #     Appx_Bundle: Never
    #     Appx_Package_Build_Mode: SideloadOnly
    #     Appx_Package_Dir: ./AppPackages/
    #     Configuration: ${{ matrix.configuration }}
    #     Platform: ${{ matrix.platform }}
    
    # - name: Remove the PFX certificate
    #   run: Remove-Item -Path "GitHubActionsWorkflow.pfx"

    - name: Upload MSIX package
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package ${{ matrix.platform }}
        path: ./AppPackages/**/*.msix

  create-tag-and-release:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Create Tag and Release
    needs: [deploy]
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, x86]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all tags and branches
                
      - name: Download all MSIX packages
        uses: actions/download-artifact@v4

      - name: Get Project version from Package.appxmanifest
        id: project-version-latest
        run: |
          [xml]$manifest = Get-Content -Path './Package.appxmanifest' # The path to the Package.appxmanifest file in the root directory
          $version = $manifest.Package.Identity.Version
          echo "::set-output name=current-version::$version"      

      - name: Create a tag and release
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        with:
          files: |
            ./**/*_${{ matrix.platform }}.msix
          tag_name: ${{ steps.project-version-latest.outputs.current-version }}
          name: v${{ steps.project-version-latest.outputs.current-version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}